import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from "react"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [djedAmount, setDjedAmount] = useState(0)
  const [shenAmount, setShenAmount] = useState(0)
  const [adaUsdRate, setAdaUsdRate] = useState(1.0)
  const [adaReserveAmt, setAdaReserveAmt] = useState(0)
  const [collateralPct, setCollateralPct] = useState(0.0)

  // useEffect(() => {

  //   let newCollateralPct

  //   if (djedAmount > 0) {

  //     const totalReserveUSD = adaReserveAmt * adaUsdRate
  //     newCollateralPct = totalReserveUSD / djedAmount

  //   } else {
  //     newCollateralPct = 0.0
  //   }

  //   setCollateralPct(newCollateralPct)


  // }, [djedAmount, shenAmount, adaUsdRate, collateralPct])
  // useEffect(() => {

  //   let newCollateralPct

  //   if (djedAmount > 0) {

  //     const totalReserveUSD = adaReserveAmt * adaUsdRate
  //     newCollateralPct = totalReserveUSD / djedAmount

  //   } else {
  //     newCollateralPct = 0.0
  //   }

  //   setCollateralPct(newCollateralPct)


  // }, [djedAmount, shenAmount, adaUsdRate, collateralPct])

  async function calCollateralization() {

    let newCollateralPct

    if (djedAmount > 0) {
      console.log(' >0')

      const totalReserveUSD = adaReserveAmt * adaUsdRate
      console.log('totalReserveUSD: ' + totalReserveUSD)
      newCollateralPct = totalReserveUSD / djedAmount

    } else {
      console.log('else')
      newCollateralPct = 0.0
    }

    setCollateralPct(newCollateralPct)
  }

  async function calcApproxShenPrice() {
    if (shenAmount > 0) {
      return adaReserveAmt * adaUsdRate / shenAmount
    } else {
      return 1.0
    }
  }

  async function mintShen(shenAmountToMint) {
    const totalShenAmount = shenAmount + shenAmountToMint
    const approxShenPrice = calcApproxShenPrice()

    const adaAmtIncres = approxShenPrice * shenAmountToMint

    setShenAmount(totalShenAmount)
    setAdaReserveAmt(adaAmtIncres)
    calCollateralization()
  }

  async function mintOneShen() {
    return mintShen(1)
  }

  async function mintDjed(djedAmountToMint) {
    const totalDjedAmount = djedAmount + djedAmountToMint
    setDjedAmount(totalDjedAmount)
    calCollateralization()
  }

  async function mintOneDjed() {
    return mintDjed(1)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>
          djedAmount: {djedAmount}
        </p>
        <p>
          shenAmount: {shenAmount}
        </p>
        <p>
          collateralPct: {collateralPct}
        </p>
        <p>
          adaUsdRate: {adaUsdRate}
        </p>
        <button type="button" onClick={() => { mintOneShen() }} >
          Mint 1 Shen
        </button>
        <button type="button" onClick={() => { mintOneDjed() }} >
          Mint 1 Djed
        </button>

      </main>
    </>
  )
}
